-- Dalat Coffee Mood: initial schema + RLS for Supabase

begin;

-- Optional helper for updated_at maintenance.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================
-- profiles
-- =========================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null default 'user',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;

-- Public can read profile metadata.
drop policy if exists "Public can view profiles" on public.profiles;
create policy "Public can view profiles"
on public.profiles
for select
to anon, authenticated
using (true);

-- Users can create only their own profile row.
drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

-- Users can update only their own profile row.
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Users can delete only their own profile row.
drop policy if exists "Users can delete own profile" on public.profiles;
create policy "Users can delete own profile"
on public.profiles
for delete
to authenticated
using (auth.uid() = id);

-- =========================
-- coffee_shops
-- =========================
create table if not exists public.coffee_shops (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  address text,
  latitude double precision,
  longitude double precision,
  ai_mood_tags text[] not null default '{}',
  image_url text,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_coffee_shops_created_by
on public.coffee_shops(created_by);

create index if not exists idx_coffee_shops_mood_tags
on public.coffee_shops using gin(ai_mood_tags);

drop trigger if exists trg_coffee_shops_updated_at on public.coffee_shops;

alter table public.coffee_shops enable row level security;

-- Everyone can view coffee shops.
drop policy if exists "Public can view coffee shops" on public.coffee_shops;
create policy "Public can view coffee shops"
on public.coffee_shops
for select
to anon, authenticated
using (true);

-- Logged-in users can create coffee shops for themselves only.
drop policy if exists "Authenticated can insert own coffee shop" on public.coffee_shops;
create policy "Authenticated can insert own coffee shop"
on public.coffee_shops
for insert
to authenticated
with check (auth.uid() = created_by);

-- Only the owner can edit their coffee shop.
drop policy if exists "Owners can update own coffee shop" on public.coffee_shops;
create policy "Owners can update own coffee shop"
on public.coffee_shops
for update
to authenticated
using (auth.uid() = created_by)
with check (auth.uid() = created_by);

-- Only the owner can delete their coffee shop.
drop policy if exists "Owners can delete own coffee shop" on public.coffee_shops;
create policy "Owners can delete own coffee shop"
on public.coffee_shops
for delete
to authenticated
using (auth.uid() = created_by);

-- =========================
-- reviews
-- =========================
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  shop_id bigint not null references public.coffee_shops(id) on delete cascade,
  rating int not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, shop_id)
);

create index if not exists idx_reviews_user_id
on public.reviews(user_id);

create index if not exists idx_reviews_shop_id
on public.reviews(shop_id);

drop trigger if exists trg_reviews_updated_at on public.reviews;

alter table public.reviews enable row level security;

-- Everyone can read reviews.
drop policy if exists "Public can view reviews" on public.reviews;
create policy "Public can view reviews"
on public.reviews
for select
to anon, authenticated
using (true);

-- Logged-in users can create reviews only as themselves.
drop policy if exists "Authenticated can insert own review" on public.reviews;
create policy "Authenticated can insert own review"
on public.reviews
for insert
to authenticated
with check (auth.uid() = user_id);

-- Only review owner can update.
drop policy if exists "Owners can update own review" on public.reviews;
create policy "Owners can update own review"
on public.reviews
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Only review owner can delete.
drop policy if exists "Owners can delete own review" on public.reviews;
create policy "Owners can delete own review"
on public.reviews
for delete
to authenticated
using (auth.uid() = user_id);

-- =========================
-- storage: coffee-images
-- =========================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'coffee-images',
  'coffee-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

DO $$
BEGIN
  ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE 'Skipping enable RLS on storage.objects: insufficient_privilege';
END$$;

drop policy if exists "Public can view coffee images" on storage.objects;
create policy "Public can view coffee images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'coffee-images');

drop policy if exists "Authenticated can upload coffee images" on storage.objects;
create policy "Authenticated can upload coffee images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'coffee-images'
  and auth.uid()::text = split_part(name, '/', 1)
);

drop policy if exists "Authenticated can update own coffee images" on storage.objects;
create policy "Authenticated can update own coffee images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'coffee-images'
  and auth.uid()::text = split_part(name, '/', 1)
)
with check (
  bucket_id = 'coffee-images'
  and auth.uid()::text = split_part(name, '/', 1)
);

drop policy if exists "Authenticated can delete own coffee images" on storage.objects;
create policy "Authenticated can delete own coffee images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'coffee-images'
  and auth.uid()::text = split_part(name, '/', 1)
);

commit;
