-- Tighten profile access and add chat history schema/RLS.

begin;

-- Restrict public access to profile rows so role metadata is not exposed to anon.
drop policy if exists "Public can view profiles" on public.profiles;
drop policy if exists "Authenticated can view profiles" on public.profiles;
create policy "Authenticated can view profiles"
on public.profiles
for select
to authenticated
using (true);

-- Persist Mood-mate chat history with explicit schema and row-level security.
create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text,
  message text,
  messages jsonb,
  prompt text,
  response text,
  chat text,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_history_user_id
on public.chat_history(user_id);

alter table public.chat_history enable row level security;

drop policy if exists "Users can view own chat history" on public.chat_history;
create policy "Users can view own chat history"
on public.chat_history
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own chat history" on public.chat_history;
create policy "Users can insert own chat history"
on public.chat_history
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own chat history" on public.chat_history;
create policy "Users can update own chat history"
on public.chat_history
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own chat history" on public.chat_history;
create policy "Users can delete own chat history"
on public.chat_history
for delete
to authenticated
using (auth.uid() = user_id);

commit;