-- Add a content-friendly schema for coffee shops and shop menu items.
-- This migration is additive and keeps the current app working while preparing
-- Supabase to become the source of truth for content data.

begin;

-- Keep the updated_at helper available for this migration.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================
-- coffee_shops
-- =========================
alter table public.coffee_shops
  add column if not exists slug text,
  add column if not exists is_active boolean not null default true;

create unique index if not exists idx_coffee_shops_slug
on public.coffee_shops(slug)
where slug is not null;

drop trigger if exists trg_coffee_shops_updated_at on public.coffee_shops;
create trigger trg_coffee_shops_updated_at
before update on public.coffee_shops
for each row
execute function public.set_updated_at();

alter table public.coffee_shops enable row level security;

drop policy if exists "Public can view coffee shops" on public.coffee_shops;
create policy "Public can view coffee shops"
on public.coffee_shops
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can insert own coffee shop" on public.coffee_shops;
create policy "Authenticated can insert own coffee shop"
on public.coffee_shops
for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists "Owners can update own coffee shop" on public.coffee_shops;
create policy "Owners can update own coffee shop"
on public.coffee_shops
for update
to authenticated
using (auth.uid() = created_by)
with check (auth.uid() = created_by);

drop policy if exists "Owners can delete own coffee shop" on public.coffee_shops;
create policy "Owners can delete own coffee shop"
on public.coffee_shops
for delete
to authenticated
using (auth.uid() = created_by);

-- =========================
-- shop_menu_items
-- =========================
create table if not exists public.shop_menu_items (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.coffee_shops(id) on delete cascade,
  name text not null,
  description text,
  price integer,
  currency text not null default 'VND',
  image_url text,
  sort_order integer not null default 0,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_shop_menu_items_shop_id
on public.shop_menu_items(shop_id);

create index if not exists idx_shop_menu_items_sort_order
on public.shop_menu_items(shop_id, sort_order);

drop trigger if exists trg_shop_menu_items_updated_at on public.shop_menu_items;
create trigger trg_shop_menu_items_updated_at
before update on public.shop_menu_items
for each row
execute function public.set_updated_at();

alter table public.shop_menu_items enable row level security;

drop policy if exists "Public can view shop menu items" on public.shop_menu_items;
create policy "Public can view shop menu items"
on public.shop_menu_items
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can insert own shop menu items" on public.shop_menu_items;
create policy "Authenticated can insert own shop menu items"
on public.shop_menu_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.coffee_shops s
    where s.id = shop_id
      and s.created_by = auth.uid()
  )
);

drop policy if exists "Owners can update own shop menu items" on public.shop_menu_items;
create policy "Owners can update own shop menu items"
on public.shop_menu_items
for update
to authenticated
using (
  exists (
    select 1
    from public.coffee_shops s
    where s.id = shop_id
      and s.created_by = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.coffee_shops s
    where s.id = shop_id
      and s.created_by = auth.uid()
  )
);

drop policy if exists "Owners can delete own shop menu items" on public.shop_menu_items;
create policy "Owners can delete own shop menu items"
on public.shop_menu_items
for delete
to authenticated
using (
  exists (
    select 1
    from public.coffee_shops s
    where s.id = shop_id
      and s.created_by = auth.uid()
  )
);

commit;
